[versions]
plugin_kotlin = "2.0.0"
plugin_moddev = "2.0.+"


minecraft = "1.20.1"
forge = "47.4.0"
kotlinForForge = "4.11.0"
parchmentmc = "2023.09.03"


[libraries]
kotlinForForge = { module = "thedarkcolour:kotlinforforge", version.ref = "kotlinForForge" }


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "plugin_kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin_kotlin" }
moddev = { id = "net.neoforged.moddev.legacyforge", version.ref = "plugin_moddev" }
